Update docker-publish.yml
Added an error check for a null value

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -16,13 +16,23 @@ jobs:
         id: check_save_release
         run: |
           latest_release=$(curl -s https://api.github.com/repos/internxt/cli/releases/latest | jq -r .tag_name)
-          echo "Latest release tag is $latest_release"
+          
+          if [ -z $latest_release ]; then
+            echo "Version lookup failed. Will try again in a moment..."
+            sleep 30
+            latest_release=$(curl -s https://api.github.com/repos/internxt/cli/releases/latest | jq -r .tag_name)
+            if [ -z $latest_release ]; then
+              echo "Version lookup failed a 2nd time. This could indicate an issue. Please investigate."
+              exit 1
+            fi
+          fi
+          echo "Latest release tag is: $latest_release" 
           
           last_known_release=$(cat .last_release 2>/dev/null || echo "")
-          echo "Last known release is $last_known_release"
+          echo "Our version is: $last_known_release"
           
           if [ "$latest_release" != "$last_known_release" ]; then
-            echo "New release detected: $latest_release"
+            echo "New release detected."
             echo "latest_release=$latest_release" >> $GITHUB_ENV
 
             echo $latest_release > .last_release
